apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
  labels: { app: monitor }
spec:
  replicas: 1
  selector: { matchLabels: { app: monitor } }
  template:
    metadata: { labels: { app: monitor } }
    spec:
      securityContext: { runAsNonRoot: true, runAsUser: 10001 }
      containers:
        - name: monitor
          image: ghcr.io/Mansi111000/uptime-status-monitor:sha-PLACEHOLDER
          env:
            - { name: DATABASE_URL, valueFrom: { secretKeyRef: { name: uptime-secrets, key: DATABASE_URL } } }
            - { name: REDIS_URL, valueFrom: { secretKeyRef: { name: uptime-secrets, key: REDIS_URL } } }
            - { name: FAIL_THRESHOLD, value: "3" }
            - { name: RECOVER_THRESHOLD, value: "2" }
            - { name: CHECK_TIMEOUT_MS, value: "5000" }
            - { name: DEFAULT_INTERVAL_SEC, value: "60" }
          resources:
            requests: { cpu: "25m", memory: "64Mi" }
            limits:   { cpu: "200m", memory: "256Mi" }
