apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels: { app: api }
spec:
  replicas: 1
  selector: { matchLabels: { app: api } }
  template:
    metadata: { labels: { app: api } }
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
      containers:
        - name: api
          image: ghcr.io/OWNER/REPO-api:dev
          ports: [{ containerPort: 8000 }]
          env:
            - { name: DATABASE_URL, valueFrom: { secretKeyRef: { name: uptime-secrets, key: DATABASE_URL } } }
            - { name: REDIS_URL, valueFrom: { secretKeyRef: { name: uptime-secrets, key: REDIS_URL } } }
          readinessProbe: { httpGet: { path: /healthz, port: 8000 }, initialDelaySeconds: 2, periodSeconds: 5 }
          livenessProbe: { httpGet: { path: /healthz, port: 8000 }, initialDelaySeconds: 5, periodSeconds: 10 }
          resources:
            requests: { cpu: "50m", memory: "128Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector: { app: api }
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
