version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/dev-db.init.sql:/docker-entrypoint-initdb.d/1-init.sql:ro
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  traefik:
    image: traefik:v3.1
    command: ["--providers.docker=true", "--entrypoints.web.address=:80"]
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/dynamic.yml:/dynamic.yml:ro

  api:
    build: ./services/api
    env_file: .env
    depends_on:
      - postgres
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
      - "traefik.http.services.api.loadbalancer.server.port=8000"

  monitor:
    build: ./services/monitor
    env_file: .env
    depends_on:
      - api
      - redis

  notifier:
    build: ./services/notifier
    env_file: .env
    depends_on:
      - api
      - redis

  status-web:
    build: ./services/status-web
    env_file: .env
    environment:
      NEXT_PUBLIC_API_URL: http://localhost/api
    depends_on:
      - api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=PathPrefix(`/`) && !PathPrefix(`/api`)"
      - "traefik.http.services.web.loadbalancer.server.port=3000"

volumes:
  pgdata:
