apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: uptime
  namespace: argocd
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: uptime
      server: https://kubernetes.default.svc
