apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Mansi111000/uptime-status.git
    targetRevision: main
    path: k8s/overlays/dev
  destination:
    name: in-cluster
    namespace: uptime
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
