apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
  namespace: uptime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
    spec:
      containers:
        - name: notifier
          # If you build locally inside the cluster node, keep Never; otherwise use IfNotPresent and a registry image
          image: uptime-status-notifier:latest
          imagePullPolicy: Never
          env:
            - name: DATABASE_URL
              # use short service name
              value: postgresql+psycopg://uptime:uptime@postgres:5432/uptime
            - name: REDIS_URL
              # use short service name
              value: redis://redis:6379/0
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: notifier-secrets
                  key: TELEGRAM_BOT_TOKEN
            - name: TELEGRAM_CHAT_ID
              valueFrom:
                secretKeyRef:
                  name: notifier-secrets
                  key: TELEGRAM_CHAT_ID
---
apiVersion: v1
kind: Secret
metadata:
  name: notifier-secrets
  namespace: uptime
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: "8260175033:AAG47nSgGtDws1810Ju9fKLoTkyfrDH_ocw"   # fill with your bot token
  TELEGRAM_CHAT_ID: "1325400360"     # fill with your chat id
