apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-web
  namespace: uptime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status-web
  template:
    metadata:
      labels:
        app: status-web
    spec:
      containers:
        - name: status-web
          image: ghcr.io/YOUR_USER/uptime-status-web:main
          env:
            - name: NEXT_PUBLIC_API_URL
              value: http://api.uptime.svc.cluster.local:8000
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: status-web
  namespace: uptime
spec:
  selector:
    app: status-web
  ports:
    - port: 3000
      targetPort: 3000
