apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Replace all four images with your GHCR names + the latest CI tag
images:
  - name: api
    newName: ghcr.io/mansi111000/uptime-status-api
    newTag: 4c621fb
  - name: monitor
    newName: ghcr.io/mansi111000/uptime-status-monitor
    newTag: 4c621fb
  - name: notifier
    newName: ghcr.io/mansi111000/uptime-status-notifier
    newTag: 4c621fb
  - name: status-web
    newName: ghcr.io/mansi111000/uptime-status-status-web
    newTag: 4c621fb

# Patch base to allow pulling from registry and (optionally) use imagePullSecrets
patches:
  - path: pull-policy.yaml
