resources:
  - ../../base
images:
  - name: ghcr.io/OWNER/REPO-api
    newTag: dev
  - name: ghcr.io/OWNER/REPO-status-web
    newTag: dev
  - name: ghcr.io/OWNER/REPO-monitor
    newTag: dev
  - name: ghcr.io/OWNER/REPO-notifier
    newTag: dev
