resources:
  - ../../base
images:
  - name: ghcr.io/mansi111000/uptime-status-api
    newTag: 8fd75a7
  - name: ghcr.io/mansi111000/uptime-status-status-web
    newTag: 8fd75a7
  - name: ghcr.io/mansi111000/uptime-status-monitor
    newTag: 8fd75a7
  - name: ghcr.io/mansi111000/uptime-status-notifier
    newTag: 8fd75a7
