resources:
  - ../../base
images:
  - name: ghcr.io/mansi111000/uptime-status-api
    newTag: 24eff70
  - name: ghcr.io/mansi111000/uptime-status-status-web
    newTag: 24eff70
  - name: ghcr.io/mansi111000/uptime-status-monitor
    newTag: 24eff70
  - name: ghcr.io/mansi111000/uptime-status-notifier
    newTag: 24eff70
