name: ci

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      OWNER: ${{ github.repository_owner }}
      REPO: ${{ github.event.repository.name }}
      GHCR_PAT: ${{ secrets.GHCR_PAT }}

    steps:
      # --- Checkout ---
      - uses: actions/checkout@v4

      # --- Normalize repo/owner (GHCR lowercase rule) ---
      - name: Normalize OWNER/REPO
        id: normalize
        run: |
          echo "owner_lc=$(echo '${{ env.OWNER }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "repo_lc=$(echo '${{ env.REPO }}'  | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      # --- Setup Docker buildx ---
      - uses: docker/setup-buildx-action@v3

      # --- Login to GHCR ---
      - name: Login to GHCR (PAT)
        if: ${{ env.GHCR_PAT != '' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ env.GHCR_PAT }}

      - name: Login to GHCR (fallback GITHUB_TOKEN)
        if: ${{ env.GHCR_PAT == '' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- Sanity plan ---
      - name: Print bake plan
        run: |
          docker buildx bake \
            --file ./docker-compose.yml \
            --set api.tags=foo --set monitor.tags=foo --set notifier.tags=foo --set status-web.tags=foo \
            --print

      # --- Build & push all images (with separate tags) ---
      - name: Build & Push Images
        uses: docker/bake-action@v5
        with:
          push: true
          files: ./docker-compose.yml
          set: |
            api.cache-to=type=registry,mode=max,ref=ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-api:buildcache
            monitor.cache-to=type=registry,mode=max,ref=ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-monitor:buildcache
            notifier.cache-to=type=registry,mode=max,ref=ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-notifier:buildcache
            status-web.cache-to=type=registry,mode=max,ref=ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-status-web:buildcache
            api.tags=ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-api:sha-${{ github.sha }}
            api.tags+=ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-api:dev-latest
            monitor.tags=ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-monitor:sha-${{ github.sha }}
            monitor.tags+=ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-monitor:dev-latest
            notifier.tags=ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-notifier:sha-${{ github.sha }}
            notifier.tags+=ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-notifier:dev-latest
            status-web.tags=ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-status-web:sha-${{ github.sha }}
            status-web.tags+=ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-status-web:dev-latest

      # --- DevSecOps: SBOM + Trivy Scanning ---
      - name: Install Syft (SBOM)
        uses: anchore/sbom-action/download-syft@v0.17.5

      - name: Install Trivy CLI
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          trivy --version

      # --- Scan API ---
      - name: Scan API Image
        continue-on-error: true
        run: |
          syft ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-api:sha-${GITHUB_SHA} -o spdx-json > sbom-api.json
          trivy image --format sarif --output trivy-api.sarif ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-api:sha-${GITHUB_SHA}
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-api.sarif
          category: trivy-api

      # --- Scan Monitor ---
      - name: Scan Monitor Image
        continue-on-error: true
        run: |
          syft ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-monitor:sha-${GITHUB_SHA} -o spdx-json > sbom-monitor.json
          trivy image --format sarif --output trivy-monitor.sarif ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-monitor:sha-${GITHUB_SHA}
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-monitor.sarif
          category: trivy-monitor

      # --- Scan Notifier ---
      - name: Scan Notifier Image
        continue-on-error: true
        run: |
          syft ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-notifier:sha-${GITHUB_SHA} -o spdx-json > sbom-notifier.json
          trivy image --format sarif --output trivy-notifier.sarif ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-notifier:sha-${GITHUB_SHA}
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-notifier.sarif
          category: trivy-notifier

      # --- Scan Status Web ---
      - name: Scan Status Web Image
        continue-on-error: true
        run: |
          syft ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-status-web:sha-${GITHUB_SHA} -o spdx-json > sbom-web.json
          trivy image --format sarif --output trivy-web.sarif ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-status-web:sha-${GITHUB_SHA}
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-web.sarif
          category: trivy-status-web
