name: ci
on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    # Resolve owner/repo dynamically; GHCR requires lowercase
    env:
      REGISTRY: ghcr.io
      OWNER: ${{ github.repository_owner }}
      REPO: ${{ github.event.repository.name }}

    steps:
      - uses: actions/checkout@v4

      - name: Normalize OWNER/REPO to lowercase (required by GHCR)
        id: normalize
        run: |
          echo "owner_lc=$(echo '${{ env.OWNER }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "repo_lc=$(echo '${{ env.REPO }}'  | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR (using GITHUB_TOKEN)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Print bake plan (sanity)
        run: |
          docker buildx bake \
            --file ./docker-compose.yml \
            --set api.tags=ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-api:sha-${GITHUB_SHA} \
            --set monitor.tags=ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-monitor:sha-${GITHUB_SHA} \
            --set notifier.tags=ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-notifier:sha-${GITHUB_SHA} \
            --set status-web.tags=ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-status-web:sha-${GITHUB_SHA} \
            --print

      # Build & push all 4 images via docker-compose as bake file
      - name: Build & push
        uses: docker/bake-action@v5
        with:
          push: true
          files: ./docker-compose.yml
          set: |
            # Keep only cache-to (first run has no cache in registry; cache-from caused 403 HEADs)
            api.cache-to=type=registry,mode=max,ref=ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-api:buildcache
            monitor.cache-to=type=registry,mode=max,ref=ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-monitor:buildcache
            notifier.cache-to=type=registry,mode=max,ref=ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-notifier:buildcache
            status-web.cache-to=type=registry,mode=max,ref=ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-status-web:buildcache
            api.tags=ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-api:sha-${{ github.sha }}
            monitor.tags=ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-monitor:sha-${{ github.sha }}
            notifier.tags=ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-notifier:sha-${{ github.sha }}
            status-web.tags=ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-status-web:sha-${{ github.sha }}

      # ---- DevSecOps (SBOM + Trivy) ----
      - name: Install Syft (SBOM)
        uses: anchore/sbom-action/download-syft@v0.17.5

      - name: Install Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          trivy_version: v0.55.0
        continue-on-error: true

      - name: Scan api
        run: |
          syft ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-api:sha-${GITHUB_SHA} -o spdx-json > sbom-api.json
          trivy image --format sarif --output trivy-api.sarif ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-api:sha-${GITHUB_SHA} || true
      - uses: github/codeql-action/upload-sarif@v3
        with: { sarif_file: trivy-api.sarif }

      - name: Scan monitor
        run: |
          syft ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-monitor:sha-${GITHUB_SHA} -o spdx-json > sbom-monitor.json
          trivy image --format sarif --output trivy-monitor.sarif ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-monitor:sha-${GITHUB_SHA} || true
      - uses: github/codeql-action/upload-sarif@v3
        with: { sarif_file: trivy-monitor.sarif }

      - name: Scan notifier
        run: |
          syft ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-notifier:sha-${GITHUB_SHA} -o spdx-json > sbom-notifier.json
          trivy image --format sarif --output trivy-notifier.sarif ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-notifier:sha-${GITHUB_SHA} || true
      - uses: github/codeql-action/upload-sarif@v3
        with: { sarif_file: trivy-notifier.sarif }

      - name: Scan status-web
        run: |
          syft ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-status-web:sha-${GITHUB_SHA} -o spdx-json > sbom-web.json
          trivy image --format sarif --output trivy-web.sarif ghcr.io/${{ steps.normalize.outputs.owner_lc }}/${{ steps.normalize.outputs.repo_lc }}-status-web:sha-${GITHUB_SHA} || true
      - uses: github/codeql-action/upload-sarif@v3
        with: { sarif_file: trivy-web.sarif }
